site_name: "Fusion Conventions: Standard Names"
site_url:
  !ENV [SITE_URL, "https://iterorganization.github.io/IMAS-Standard-Names/"]

plugins:
  - include-markdown
  - macros:
      verbose: true
      modules:
        - docs.grammar_macros
  - search
  - table-reader
  - mike:
      canonical_version: latest
      version_selector: true
      css_dir: stylesheets
      javascript_dir: javascripts

watch:
  - imas_standard_names/grammar/specification.yml
  - imas_standard_names/grammar/vocabularies/
  - imas_standard_names/resources/standard_names/
  - docs/grammar_macros.py

nav:
  - Home: index.md
  - Grammar Reference: grammar-reference.md
  - Guidelines: guidelines.md
  - Specification: specification.md
  - Quick Start: quickstart.md
  - Style Guide: style-guide.md
  - Catalog: catalog.md
  - Examples:
    - IMAS Magnetics Diagnostic: magnetics-example.md
  - Provenance: provenance.md
  - Reductions: reductions.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top

extra:
  version:
    provider: mike

# Enable latex/math notation
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
