name: Install imas-standard-names project
description: Set up Python with uv and sync project dependencies (all extras, excluding dev) for testing and documentation.

inputs:
  python-version:
    description: "Python version to set up."
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    - name: Sync dependencies (no dev)
      shell: bash
      run: |
        uv sync --no-dev
