machine: WEST
facility: CEA Cadarache
location: Cadarache, France
operational_status: operational
last_updated: "2025-11-03"
sources:
  - url: https://fusionwiki.ciemat.es/wiki/WEST
    accessed: "2025-11-03"
    description: "FusionWiki comprehensive database"
  - url: https://west.cea.fr/
    description: "CEA WEST page"

geometry:
  major_radius:
    value: 2.5
    unit: m
    symbol: R_0
  minor_radius:
    value: 0.5
    unit: m
    symbol: a
  plasma_volume:
    value: 15
    unit: m^3
    symbol: V_p
  elongation:
    value: 1.4
    unit: "1"
    symbol: kappa
  triangularity:
    value: 0.3
    unit: "1"
    symbol: delta
  aspect_ratio:
    value: 5.0
    unit: "1"
    symbol: A
    note: "R_0/a"

physics:
  toroidal_magnetic_field:
    value: 3.7
    unit: T
    symbol: B_T
    location: "at major radius R_0"
  plasma_current:
    value: 1.0
    unit: MA
    symbol: I_p
    note: "typical maximum"
  edge_safety_factor:
    value: 4.0
    unit: "1"
    symbol: q_95
  electron_density:
    value: 5.0e19
    unit: m^-3
    symbol: n_e
    note: "typical"
  ion_temperature:
    value: 2.0
    unit: keV
    symbol: T_i
    note: "typical"
  electron_temperature:
    value: 2.5
    unit: keV
    symbol: T_e
    note: "typical"
  energy_confinement_time:
    value: 0.1
    unit: s
    symbol: tau_E
    note: "typical"

