"""Auto-generated grammar models.

Auto-generated grammar models.

This file was generated by imas_standard_names.grammar_codegen.generate
from imas_standard_names/grammar/specification.yml. Do not edit manually."""

from __future__ import annotations

from enum import StrEnum

class Component(StrEnum):
    RADIAL = "radial"
    TOROIDAL = "toroidal"
    VERTICAL = "vertical"
    POLOIDAL = "poloidal"
    PARALLEL = "parallel"
    DIAMAGNETIC = "diamagnetic"
    NORMAL = "normal"
    TANGENTIAL = "tangential"
    BINORMAL = "binormal"
    X = "x"
    Y = "y"
    Z = "z"


class Subject(StrEnum):
    ELECTRON = "electron"
    ION = "ion"
    DEUTERIUM = "deuterium"
    TRITIUM = "tritium"
    HELIUM = "helium"
    IMPURITY_SPECIES = "impurity_species"
    FAST_ION = "fast_ion"
    NEUTRAL = "neutral"
    RUNAWAY_ELECTRON = "runaway_electron"


class GeometricBase(StrEnum):
    POSITION = "position"
    VERTEX = "vertex"
    CENTROID = "centroid"
    OUTLINE = "outline"
    CONTOUR = "contour"
    DISPLACEMENT = "displacement"
    OFFSET = "offset"
    TRAJECTORY = "trajectory"
    EXTENT = "extent"
    SURFACE_NORMAL = "surface_normal"
    SENSOR_NORMAL = "sensor_normal"
    TANGENT_VECTOR = "tangent_vector"


class Object(StrEnum):
    ANTENNA_STRAP = "antenna_strap"
    BOLOMETER = "bolometer"
    CAMERA = "camera"
    CORRECTION_COIL = "correction_coil"
    DIAMAGNETIC_LOOP = "diamagnetic_loop"
    DIVERTOR_TILE = "divertor_tile"
    ELECTRON_CYCLOTRON_HEATING_ANTENNA = "electron_cyclotron_heating_antenna"
    FLUX_LOOP = "flux_loop"
    GAMMA_RAY_DETECTOR = "gamma_ray_detector"
    INFRARED_CAMERA = "infrared_camera"
    INTERFEROMETER_BEAM = "interferometer_beam"
    ION_CYCLOTRON_HEATING_ANTENNA = "ion_cyclotron_heating_antenna"
    ISOTOPE = "isotope"
    LANGMUIR_PROBE = "langmuir_probe"
    LIMITER_TILE = "limiter_tile"
    LOWER_HYBRID_ANTENNA = "lower_hybrid_antenna"
    NEUTRAL_BEAM_INJECTOR = "neutral_beam_injector"
    NEUTRON_DETECTOR = "neutron_detector"
    POLOIDAL_FIELD_COIL = "poloidal_field_coil"
    POLOIDAL_MAGNETIC_FIELD_PROBE = "poloidal_magnetic_field_probe"
    RADIAL_MAGNETIC_FIELD_PROBE = "radial_magnetic_field_probe"
    RECIPROCATING_PROBE = "reciprocating_probe"
    REFLECTOMETER_ANTENNA = "reflectometer_antenna"
    REFLECTOMETER_DETECTOR = "reflectometer_detector"
    ROGOWSKI_COIL = "rogowski_coil"
    SADDLE_LOOP = "saddle_loop"
    SOFT_XRAY_DETECTOR = "soft_xray_detector"
    SOFT_XRAY_DETECTOR_LINE_OF_SIGHT_FIRST_POINT = (
        "soft_xray_detector_line_of_sight_first_point"
    )
    SOFT_XRAY_DETECTOR_LINE_OF_SIGHT_SECOND_POINT = (
        "soft_xray_detector_line_of_sight_second_point"
    )
    SPECTROMETER = "spectrometer"
    SPECTROMETER_LINE_OF_SIGHT_FIRST_POINT = "spectrometer_line_of_sight_first_point"
    SPECTROMETER_LINE_OF_SIGHT_SECOND_POINT = "spectrometer_line_of_sight_second_point"
    THOMSON_SCATTERING_DETECTOR = "thomson_scattering_detector"
    THOMSON_SCATTERING_LASER = "thomson_scattering_laser"
    TOROIDAL_FIELD_COIL = "toroidal_field_coil"
    TOROIDAL_MAGNETIC_FIELD_PROBE = "toroidal_magnetic_field_probe"
    TRIM_COIL = "trim_coil"
    VISIBLE_CAMERA = "visible_camera"


class Position(StrEnum):
    ACTIVE_LIMITER_POINT = "active_limiter_point"
    CLOSEST_WALL_POINT = "closest_wall_point"
    CORE_REGION = "core_region"
    CURRENT_CENTER = "current_center"
    DIVERTOR_REGION = "divertor_region"
    DIVERTOR_TARGET = "divertor_target"
    EDGE_REGION = "edge_region"
    FIRST_POINT_OF_INTERFEROMETER_BEAM = "first_point_of_interferometer_beam"
    FIRST_WALL = "first_wall"
    FLUX_SURFACE = "flux_surface"
    INNER_DIVERTOR_TARGET = "inner_divertor_target"
    INNER_MIDPLANE = "inner_midplane"
    LAST_CLOSED_FLUX_SURFACE = "last_closed_flux_surface"
    LIMITER = "limiter"
    MAGNETIC_AXIS = "magnetic_axis"
    MIDPLANE = "midplane"
    MINIMUM_SAFETY_FACTOR = "minimum_safety_factor"
    OUTBOARD_MIDPLANE = "outboard_midplane"
    OUTBOARD_MIDPLANE_HEIGHT = "outboard_midplane_height"
    OUTER_DIVERTOR_TARGET = "outer_divertor_target"
    OUTER_MIDPLANE = "outer_midplane"
    PLASMA_BOUNDARY = "plasma_boundary"
    PRIMARY_STRIKE_POINT = "primary_strike_point"
    PRIMARY_X_POINT = "primary_x_point"
    REFERENCE_MAJOR_RADIUS = "reference_major_radius"
    REFERENCE_POSITION = "reference_position"
    SCRAPE_OFF_LAYER = "scrape_off_layer"
    SECOND_POINT_OF_INTERFEROMETER_BEAM = "second_point_of_interferometer_beam"
    SPECTRAL_LINE = "spectral_line"
    THIRD_POINT_OF_INTERFEROMETER_BEAM = "third_point_of_interferometer_beam"


class Process(StrEnum):
    CONDUCTION = "conduction"
    CONVECTION = "convection"
    DIFFUSION = "diffusion"
    NEOCLASSICAL = "neoclassical"
    TURBULENT = "turbulent"
    ANOMALOUS = "anomalous"
    OHMIC = "ohmic"
    ELECTRON_CYCLOTRON_HEATING = "electron_cyclotron_heating"
    ION_CYCLOTRON_HEATING = "ion_cyclotron_heating"
    LOWER_HYBRID_CURRENT_DRIVE = "lower_hybrid_current_drive"
    NEUTRAL_BEAM_INJECTION = "neutral_beam_injection"
    ELECTRON_CYCLOTRON_CURRENT_DRIVE = "electron_cyclotron_current_drive"
    RADIATION = "radiation"
    RECOMBINATION = "recombination"
    IONIZATION = "ionization"
    CHARGE_EXCHANGE = "charge_exchange"
    INDUCTION = "induction"
    BOOTSTRAP = "bootstrap"
    RESISTIVE = "resistive"
    VISCOUS = "viscous"
    MAGNETOHYDRODYNAMIC = "magnetohydrodynamic"
    EXTERNAL_COIL = "external_coil"
    EDDY_CURRENT = "eddy_current"
    PASSIVE_STRUCTURE = "passive_structure"
    DISRUPTION = "disruption"
    HALO = "halo"


class GenericPhysicalBase(StrEnum):
    AREA = "area"
    CURRENT = "current"
    ENERGY = "energy"
    FLUX = "flux"
    FREQUENCY = "frequency"
    NUMBER_DENSITY = "number_density"
    POWER = "power"
    PRESSURE = "pressure"
    TEMPERATURE = "temperature"
    VELOCITY = "velocity"
    VOLTAGE = "voltage"
    VOLUME = "volume"

__all__ = [
    "Component",
    "Subject",
    "GeometricBase",
    "Object",
    "Position",
    "Process",
    "GenericPhysicalBase",
]
