"""Auto-generated tag models.

This file was generated by imas_standard_names.grammar_codegen.generate
from imas_standard_names/grammar/vocabularies/tags.yml. Do not edit manually."""

from __future__ import annotations

from enum import StrEnum


class PhysicsDomain(StrEnum):
    """Physics domain classification for IMAS standard names."""

    EQUILIBRIUM = "equilibrium"
    TRANSPORT = "transport"
    CORE_PLASMA_PHYSICS = "core_plasma_physics"
    TURBULENCE = "turbulence"
    MAGNETOHYDRODYNAMICS = "magnetohydrodynamics"
    AUXILIARY_HEATING = "auxiliary_heating"
    CURRENT_DRIVE = "current_drive"
    WAVES = "waves"
    EDGE_PLASMA_PHYSICS = "edge_plasma_physics"
    PLASMA_WALL_INTERACTIONS = "plasma_wall_interactions"
    DIVERTOR_PHYSICS = "divertor_physics"
    FUELING = "fueling"
    FAST_PARTICLES = "fast_particles"
    RUNAWAY_ELECTRONS = "runaway_electrons"
    PARTICLE_MEASUREMENT_DIAGNOSTICS = "particle_measurement_diagnostics"
    ELECTROMAGNETIC_WAVE_DIAGNOSTICS = "electromagnetic_wave_diagnostics"
    RADIATION_MEASUREMENT_DIAGNOSTICS = "radiation_measurement_diagnostics"
    MAGNETIC_FIELD_DIAGNOSTICS = "magnetic_field_diagnostics"
    MECHANICAL_MEASUREMENT_DIAGNOSTICS = "mechanical_measurement_diagnostics"
    PLASMA_MEASUREMENT_DIAGNOSTICS = "plasma_measurement_diagnostics"
    SPECTROSCOPY = "spectroscopy"
    NEUTRONICS = "neutronics"
    PLASMA_CONTROL = "plasma_control"
    MACHINE_OPERATIONS = "machine_operations"
    PLASMA_INITIATION = "plasma_initiation"
    MAGNETIC_FIELD_SYSTEMS = "magnetic_field_systems"
    STRUCTURAL_COMPONENTS = "structural_components"
    PLANT_SYSTEMS = "plant_systems"
    DATA_MANAGEMENT = "data_management"
    COMPUTATIONAL_WORKFLOW = "computational_workflow"
    GENERAL = "general"
    GYROKINETICS = "gyrokinetics"


PHYSICS_DOMAIN_DESCRIPTIONS: dict[str, str] = {
    "equilibrium": "MHD equilibrium, flux surfaces, magnetic geometry, coordinate systems",
    "transport": "Transport coefficients, fluxes, neoclassical and anomalous transport modeling",
    "core_plasma_physics": "Core plasma profiles, kinetic quantities, global parameters, integrated quantities",
    "turbulence": "Turbulence physics, fluctuations, turbulent transport, correlation analysis",
    "magnetohydrodynamics": "MHD stability, disruptions, instabilities, sawteeth, tearing modes",
    "auxiliary_heating": "Auxiliary heating systems including neutral beam, electron cyclotron, ion cyclotron, and lower hybrid",
    "current_drive": "Non-inductive current drive physics, efficiency, and profile control",
    "waves": "Wave propagation, RF physics, wave-particle interactions, dispersion",
    "edge_plasma_physics": "Scrape-off layer, divertor physics, plasma-wall interactions, recycling",
    "plasma_wall_interactions": "First wall, plasma-facing components, erosion, deposition, material migration",
    "divertor_physics": "Divertor target loads, detachment, particle and heat exhaust",
    "fueling": "Gas injection, pellet injection, shattered pellet injection, fueling systems",
    "fast_particles": "Fast ion and electron distributions, energetic particles, slowing-down",
    "runaway_electrons": "Runaway electron physics, avalanche generation, loss mechanisms",
    "particle_measurement_diagnostics": "Thomson scattering and particle-based diagnostic measurements",
    "electromagnetic_wave_diagnostics": "Interferometry, polarimetry, reflectometry, and wave-based diagnostics",
    "radiation_measurement_diagnostics": "Bolometry, X-ray diagnostics, bremsstrahlung, imaging systems",
    "magnetic_field_diagnostics": "Magnetic diagnostics, flux loops, Rogowski coils, diamagnetic measurements",
    "mechanical_measurement_diagnostics": "Mechanical and structural measurement diagnostics, strain, vibration",
    "plasma_measurement_diagnostics": "General plasma parameter measurement diagnostics",
    "spectroscopy": "Emission spectroscopy, charge exchange, motional Stark effect, impurity diagnostics",
    "neutronics": "Neutron diagnostics, fusion product measurements, activation",
    "plasma_control": "Plasma position and shape control, feedback systems, electromagnetic coupling",
    "machine_operations": "Pulse scheduling, workflow management, operational metadata",
    "plasma_initiation": "Plasma startup, breakdown, initiation physics, early heating phase",
    "magnetic_field_systems": "Magnetic coil systems, superconducting magnets, field generation infrastructure",
    "structural_components": "Vacuum vessel, cryostat, structural support systems",
    "plant_systems": "Power supplies, cooling systems, vacuum systems, plant infrastructure",
    "data_management": "Summary data products, integrated analysis results, data archival",
    "computational_workflow": "Auxiliary data, atomic and molecular data, geometry definitions, computational tools",
    "general": "Universal plasma physics quantities appearing across multiple IDS",
    "gyrokinetics": "Gyrokinetic theory, simulation, and turbulence modeling",
}

PHYSICS_DOMAINS: tuple[str, ...] = (
    "equilibrium",
    "transport",
    "core_plasma_physics",
    "turbulence",
    "magnetohydrodynamics",
    "auxiliary_heating",
    "current_drive",
    "waves",
    "edge_plasma_physics",
    "plasma_wall_interactions",
    "divertor_physics",
    "fueling",
    "fast_particles",
    "runaway_electrons",
    "particle_measurement_diagnostics",
    "electromagnetic_wave_diagnostics",
    "radiation_measurement_diagnostics",
    "magnetic_field_diagnostics",
    "mechanical_measurement_diagnostics",
    "plasma_measurement_diagnostics",
    "spectroscopy",
    "neutronics",
    "plasma_control",
    "machine_operations",
    "plasma_initiation",
    "magnetic_field_systems",
    "structural_components",
    "plant_systems",
    "data_management",
    "computational_workflow",
    "general",
    "gyrokinetics",
)

TAG_TO_PHYSICS_DOMAIN: dict[str, str] = {
    "equilibrium": "equilibrium",
    "transport": "transport",
    "turbulence": "turbulence",
    "magnetics": "magnetic_field_diagnostics",
    "waves": "waves",
    "fueling": "fueling",
    "spectroscopy": "spectroscopy",
    "neutronics": "neutronics",
    "mhd": "magnetohydrodynamics",
    "edge-physics": "edge_plasma_physics",
    "core-physics": "core_plasma_physics",
    "fast-particles": "fast_particles",
    "runaway-electrons": "runaway_electrons",
    "radiation-diagnostics": "radiation_measurement_diagnostics",
    "coils-and-control": "plasma_control",
    "pulse-management": "machine_operations",
    "wall-and-structures": "plasma_wall_interactions",
    "plasma-initiation": "plasma_initiation",
    "fundamental": "general",
    "nbi": "auxiliary_heating",
    "ec-heating": "auxiliary_heating",
    "ic-heating": "auxiliary_heating",
    "lh-heating": "auxiliary_heating",
    "thomson-scattering": "particle_measurement_diagnostics",
    "interferometry": "electromagnetic_wave_diagnostics",
    "reflectometry": "electromagnetic_wave_diagnostics",
    "imaging": "radiation_measurement_diagnostics",
    "data-products": "data_management",
    "utilities": "computational_workflow",
}

__all__ = [
    "PhysicsDomain",
    "PHYSICS_DOMAINS",
    "PHYSICS_DOMAIN_DESCRIPTIONS",
    "TAG_TO_PHYSICS_DOMAIN",
]
